version: '3'

services:
  minio:
    image: minio/minio
    ports:
        - 9000:9000
        - 9001:9001
    environment:
        - MINIO_ACCESS_KEY=username
        - MINIO_SECRET_KEY=password
    volumes:
        - /path/to/data:/data
        - /path/to/config:/root/.minio
    command: server --console-address ":9001" /data
  minio-client:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - /path/to/config:/root/.mc
    entrypoint: ["/bin/sh", "-c"]
    command: >
      mc config host add myminio http://minio:9000 username password &&
      mc alias set myminio http://minio:9000

    tty: true

#volumes:
#  minio_data:
